version: "3.7"
services:
  http:
    build: http
    ports:
      - 81:80
      - 444:443
    volumes:
      - ./../:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./http/conf/000-default.conf:/etc/apache2/sites-available/000-default.conf
    user:
      1000:1000
    networks:
      analisis-crediticios:
        aliases:
          - laravel.local
    env_file:
      - ./.env
  database:
    build: database
    ports: 
      - 3308:3306
    volumes:
      - ./database/var/lib/mysql:/var/lib/mysql
    networks:
      - analisis-crediticios
    domainname: mysql
    hostname: mysql
    env_file:
      - ./.env
    restart: on-failure
networks:
  analisis-crediticios:
    driver: bridge
